# Generated by Django 5.2.5 on 2025-08-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('Internship', 'intern'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
