# Generated by Django 5.2.5 on 2025-08-27 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_experience_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_industry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_web',
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='institute',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='passing_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('Internship', 'intern'), ('Other', 'other')], default='other', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=22, null=True)),
                ('company_web', models.URLField(blank=True, null=True)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('company_industry', models.CharField(blank=True, choices=[('healthcare', 'Healthcare & Medical'), ('it', 'Information Technology & Software'), ('education', 'Education & Training'), ('finance', 'Finance & Accounting'), ('sales', 'Sales & Marketing'), ('engineering', 'Engineering & Manufacturing'), ('hospitality', 'Hospitality & Tourism'), ('transport', 'Transportation & Logistics'), ('legal', 'Legal & Compliance'), ('arts', 'Arts, Media & Design'), ('other', 'Other')], max_length=50, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
