# Generated by Django 5.2.5 on 2025-08-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Full Time', 'full_time'), ('Part Time', 'part_time'), ('Internship', 'intern'), ('Other', 'other')], default='other', max_length=20, null=True),
        ),
    ]
