# Generated by Django 5.2.5 on 2025-08-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company_company_logo_alter_experience_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Full Time', 'full_time'), ('part_time', 'Part Time'), ('intern', 'Internship'), ('Other', 'other')], default='other', max_length=20, null=True),
        ),
    ]
