# Generated by Django 5.2.5 on 2025-08-28 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_experience_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employers', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Full Time', 'full_time'), ('part_time', 'Part Time'), ('intern', 'Internship'), ('other', 'Other')], default='other', max_length=20, null=True),
        ),
    ]
