# Generated by Django 5.2.5 on 2025-08-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_company_name_alter_experience_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='job_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('Internship', 'intern'), ('other', 'Other')], default='other', max_length=20, null=True),
        ),
    ]
