# Generated by Django 5.2.5 on 2025-08-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_experience_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
        migrations.AddField(
            model_name='user',
            name='industry',
            field=models.CharField(blank=True, choices=[('healthcare', 'Healthcare & Medical'), ('it', 'Information Technology & Software'), ('education', 'Education & Training'), ('finance', 'Finance & Accounting'), ('sales', 'Sales & Marketing'), ('engineering', 'Engineering & Manufacturing'), ('hospitality', 'Hospitality & Tourism'), ('transport', 'Transportation & Logistics'), ('legal', 'Legal & Compliance'), ('arts', 'Arts, Media & Design'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Full Time', 'full_time'), ('Part Time', 'part_time'), ('Internship', 'intern'), ('other', 'Other')], default='other', max_length=20, null=True),
        ),
    ]
