# Generated by Django 5.2.5 on 2025-08-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_company_name_user_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='job_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('Part Time', 'part_time'), ('Internship', 'intern'), ('Other', 'other')], default='other', max_length=20, null=True),
        ),
    ]
