# Generated by Django 5.2.5 on 2025-08-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_experience_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Full Time', 'full_time'), ('Part Time', 'part_time'), ('Internship', 'intern'), ('Other', 'other')], default='other', max_length=20, null=True),
        ),
    ]
