# Generated by Django 5.2.5 on 2025-09-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_experience_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='job_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('Part Time', 'part_time'), ('intern', 'Internship'), ('Other', 'other')], default='other', max_length=20, null=True),
        ),
    ]
